### ISSUE TITLE
[ML] 2.5 Расширить датасет

### ISSUE THREAD

**Issue by ayakovlev18214** [evraz42/SeparatorsCompTech2020#4]
Найти методы аугментации данных для уравнивания количества данных в датасете

**Comment by Vakurin** [comment]
`
# Получение всех имен в директорию
def list_all_files_in_directory(mypath = 'new_data'):
    from os import listdir
    from os.path import isfile, join

    onlyfiles = [f for f in listdir(mypath) if isfile(join(mypath, f))]
    
    all_files = []
    for ele in sorted(onlyfiles):
        all_files.append(ele)
    return all_files

def get_all_image():
    all_images_in_directory = list_all_files_in_directory('clear_dataset/left/2')
    images = []
    all_images_in_directory = all_images_in_directory
    for i in range(len(all_images_in_directory)):
        image = cv2.imread("clear_dataset/left/2/".format(all_images_in_directory[i]))
        # CV2 Manipulation
        
        # CV2 Save File `

**Comment by Vakurin** [comment]
`def get_all_image():
    all_images_in_directory = list_all_files_in_directory('clear_dataset/left/2')
    images = []
    all_images_in_directory = all_images_in_directory
    for i in range(len(all_images_in_directory)):
        image = cv2.imread("clear_dataset/left/2/".format(all_images_in_directory[i]))
        # CV2 Manipulation
        
        # CV2 Save File 

`

**Comment by Vakurin** [comment]
def get_all_image():
    all_images_in_directory = list_all_files_in_directory('clear_dataset/left/2')
    images = []
    all_images_in_directory = all_images_in_directory
    for i in range(len(all_images_in_directory)):
        image = cv2.imread("clear_dataset/left/2/".format(all_images_in_directory[i]))

**Comment by ayakovlev18214** [comment]
Done. Количество изображений каждого положения флажка увеличено с 50 до 350-400.
