### ISSUE TITLE
[ML] 5. Сделать базовую модель

### ISSUE THREAD

**Issue by ayakovlev18214** [evraz42/SeparatorsCompTech2020#7]
Необходимо обучить базовую модель для распознавания положения флажка.

**Comment by Vakurin** [comment]
Сделали базовую модель с точностью ~75-80%
Выделены основные признаки сети:
<img width="326" alt="image" src="https://user-images.githubusercontent.com/22254882/73455420-97dfa200-43a2-11ea-8325-f3c0b385a565.png">
